name: CI
on:
  workflow_dispath:
    push:
      branches:
        - main

permissions:
  contents: write

jobs:
  generate-version:
    runs-on: ubunto-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Gerar nova versão baseado no Conventional Commits
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        env:
          HUSKY: 0
        with:
          preset: conventionalcommits
          skip-on-empty: false
